package com.sinexperiencia.sinexperiencia.exceptions;

public class UserAlreadyExistsException {

}
